/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 comp-room.glb 
Author: Doña Juana (https://sketchfab.com/DoniaJuana)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/our-little-living-room-b79bf1c134d94c899e4b316fbe53efcc
Title: Our little living room
*/

import React, { useEffect } from 'react'
import { useGLTF, useTexture } from '@react-three/drei'
import * as THREE from 'three';

export function CompRoom(props) {
  const matcapTexture =useTexture('/images/textures/mat1.png');
  const { nodes, materials } = useGLTF('/video-models/comp-room.glb')

const curtainMaterial= new THREE.MeshPhongMaterial({color: '#d90429'});

const bodyMaterial = new THREE.MeshStandardMaterial({
    map: matcapTexture,
})

  useEffect(() => {
  if (materials.Floor) {
    materials.Floor.color.set('#f6f6f6');
    materials.Floor.roughness = 0.3;
    materials.Floor.metalness = 0.1;
  }

  if (materials.Wall) {
    materials.Wall.color.set('#faf3dd');
  }

  if (materials['PC.001']) {
    materials['PC.001'].color.set('#80ed99');
    materials['PC.001'].metalness = 0.6;
    materials['PC.001'].roughness = 0.4;
  }

  if (materials['Material.011']) {
    materials['Material.011'].color.set('#cdb4db');
  }
}, [materials]);

  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.007}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0, 243.393, -16.073]} rotation={[-Math.PI / 2, 0, 0]} scale={[300, 350, 240]}>
            {/* <mesh geometry={nodes.Room_Wall_2_0.geometry} material={materials.Wall_2} /> */}
            <mesh geometry={nodes.Room_Wall_2_0.geometry} material={curtainMaterial} />
            {/* <mesh geometry={nodes.Room_Wall_0.geometry} material={materials.Wall} /> */}
            <mesh geometry={nodes.Room_Wall_0.geometry} material={bodyMaterial} />
            <mesh geometry={nodes.Room_Floor_0.geometry} material={materials.Floor} />
          </group>
          <group position={[0, 165.601, -338.645]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={100}>
            <group scale={[1.656, 1, 2.176]}>
              <group position={[-0.59, -0.023, 0.025]}>
                <mesh geometry={nodes.WindowL_Window_material_0.geometry} material={materials.Window_material} />
                <mesh geometry={nodes.WindowL_Glass_material_0.geometry} material={materials.Glass_material} />
                <mesh geometry={nodes.Handle_Plastic_Handle_material_0.geometry} material={materials.Plastic_Handle_material} position={[0.035, -0.036, 0.475]} />
              </group>
              <group position={[0.59, -0.063, 0.025]}>
                <mesh geometry={nodes.WindowR_Window_material_0.geometry} material={materials.Window_material} />
                <mesh geometry={nodes.WindowR_Glass_material_0.geometry} material={materials.Glass_material} />
                <mesh geometry={nodes.Handle001_Plastic_Handle_material_0.geometry} material={materials.Plastic_Handle_material} position={[-0.035, -0.035, 0.475]} />
              </group>
              <mesh geometry={nodes.WindowFrame_Window_material_0.geometry} material={materials.Window_material} />
              <mesh geometry={nodes.Windows_Sill_Sill_material_0.geometry} material={materials.Sill_material} position={[0, -0.1, 0]} />
            </group>
          </group>
          <group position={[-228.595, 111.649, 125.946]} rotation={[-Math.PI / 2, 0, 0]} scale={[58.175, 139.542, 6.546]}>
            <mesh geometry={nodes.Cube002_Desk_0.geometry} material={materials.Desk} />
            <mesh geometry={nodes.Cube002_PC001_0.geometry} material={materials['PC.001']} />
            <mesh geometry={nodes.Cube002_Screen_Light_0.geometry} material={materials.Screen_Light} />
            <mesh geometry={nodes.Cube001_Desk_0.geometry} material={materials.Desk} position={[0, 0, 34.583]} scale={[1.107, 1, 21.318]} />
            <mesh geometry={nodes.Cube003_Desk_0.geometry} material={materials.Desk} position={[0.01, -0.761, -7.495]} scale={[0.67, 0.013, 1.236]} />
            <mesh geometry={nodes.Cube004_Desk_0.geometry} material={materials.Desk} position={[0.01, 0.761, -7.495]} scale={[0.67, 0.013, 1.236]} />
          </group>
          <group position={[-248.102, 121.5, 96.943]} rotation={[-Math.PI / 2, 0, 0]} scale={[23.06, 30.53, 3.137]}>
            <mesh geometry={nodes.PC_PC_0.geometry} material={materials.material} />
            <mesh geometry={nodes.PC_Material_0.geometry} material={materials.Material} />
            <mesh geometry={nodes.PC_Mousepad_0.geometry} material={materials.Mousepad} />
          </group>
          <group position={[-281.172, 161.075, -262.433]} rotation={[Math.PI / 2, 0, 2.39]} scale={[-9.388, 9.388, 0.191]}>
            <mesh geometry={nodes.Cylinder006_PC_0.geometry} material={materials.material} />
            <mesh geometry={nodes.Cylinder006_Blue_Controller_0.geometry} material={materials.Blue_Controller} />
            <mesh geometry={nodes.Cylinder006_Screen_0.geometry} material={materials.Screen} />
            <mesh geometry={nodes.Cylinder006_Red_Controller_0.geometry} material={materials.Red_Controller} />
          </group>
          <group position={[-264.465, 247.658, 232.367]} rotation={[-Math.PI / 2, 0, 0]} scale={[160.549, 357.813, 124.283]}>
            <mesh geometry={nodes.Cube015_Printer_0.geometry} material={materials.Printer} />
            <mesh geometry={nodes.Cube015_PC_0.geometry} material={materials.material} />
            <mesh geometry={nodes.Cube015_Material014_0.geometry} material={materials['Material.014']} />
            <mesh geometry={nodes.Cube015_Material002_0.geometry} material={materials['Material.002']} />
          </group>
          <group position={[-273.044, 388.381, -333.08]} rotation={[-Math.PI / 2, 0, 0]} scale={[201.96, 45.561, 355.611]}>
            <mesh geometry={nodes.Cube016_Material015_0.geometry} material={materials['Material.015']} />
            <mesh geometry={nodes.Cube016_Material011_0.geometry} material={materials['Material.011']} />
          </group>
          <group position={[-270.38, 399.372, -319.939]} rotation={[-Math.PI / 2, 0, 0]} scale={[235.809, 72.878, 465.821]}>
            <mesh geometry={nodes.Cube017_Material016_0.geometry} material={materials['Material.016']} />
            <mesh geometry={nodes.Cube017_Material011_0.geometry} material={materials['Material.011']} />
          </group>
          <group position={[-268.749, 391.892, -300.131]} rotation={[-Math.PI / 2, 0, 0]} scale={[235.809, 109.916, 387.652]}>
            <mesh geometry={nodes.Cube018_Material017_0.geometry} material={materials['Material.017']} />
            <mesh geometry={nodes.Cube018_Material011_0.geometry} material={materials['Material.011']} />
          </group>
          <group position={[-270.571, 386.703, -283.926]} rotation={[-Math.PI / 2, 0, 0]} scale={[235.809, 28.855, 348.755]}>
            <mesh geometry={nodes.Cube019_Material018_0.geometry} material={materials['Material.018']} />
            <mesh geometry={nodes.Cube019_Material011_0.geometry} material={materials['Material.011']} />
          </group>
          <group position={[-268.861, 388.664, -217.542]} rotation={[-Math.PI / 2, 0, 0]} scale={[201.96, 33.29, 355.611]}>
            <mesh geometry={nodes.Cube020_Material022_0.geometry} material={materials['Material.022']} />
            <mesh geometry={nodes.Cube020_Material011_0.geometry} material={materials['Material.011']} />
          </group>
          <group position={[-266.197, 389.282, -266.013]} rotation={[-Math.PI / 2, 0, 0]} scale={[235.809, 133.15, 361.161]}>
            <mesh geometry={nodes.Cube021_Material023_0.geometry} material={materials['Material.023']} />
            <mesh geometry={nodes.Cube021_Material011_0.geometry} material={materials['Material.011']} />
          </group>
          <group position={[-264.566, 392.174, -241.697]} rotation={[-Math.PI / 2, 0, 0]} scale={[235.809, 95.763, 387.652]}>
            <mesh geometry={nodes.Cube022_Material020_0.geometry} material={materials['Material.020']} />
            <mesh geometry={nodes.Cube022_Material011_0.geometry} material={materials['Material.011']} />
          </group>
          <group position={[-266.388, 387.887, -226.694]} rotation={[-Math.PI / 2, 0, 0]} scale={[235.809, 36.293, 348.755]}>
            <mesh geometry={nodes.Cube023_Material021_0.geometry} material={materials['Material.021']} />
            <mesh geometry={nodes.Cube023_Material011_0.geometry} material={materials['Material.011']} />
          </group>
          <group position={[-261.657, 379.592, -145.688]} rotation={[-Math.PI / 2, 0, 0]} scale={[201.96, 106.694, 265.912]}>
            <mesh geometry={nodes.Cube024_Material015_0.geometry} material={materials['Material.015']} />
            <mesh geometry={nodes.Cube024_Material011_0.geometry} material={materials['Material.011']} />
          </group>
          <group position={[-260.356, 400.126, -196.627]} rotation={[-Math.PI / 2, 0, 0]} scale={[235.809, 72.878, 465.821]}>
            <mesh geometry={nodes.Cube025_Material024_0.geometry} material={materials['Material.024']} />
            <mesh geometry={nodes.Cube025_Material011_0.geometry} material={materials['Material.011']} />
          </group>
          <group position={[-252.817, 392.646, -177.273]} rotation={[-Math.PI / 2, 0, 0]} scale={[235.809, 109.916, 387.652]}>
            <mesh geometry={nodes.Cube026_Material025_0.geometry} material={materials['Material.025']} />
            <mesh geometry={nodes.Cube026_Material011_0.geometry} material={materials['Material.011']} />
          </group>
          <group position={[-259.638, 387.457, -161.069]} rotation={[-Math.PI / 2, 0, 0]} scale={[235.809, 28.855, 348.755]}>
            <mesh geometry={nodes.Cube027_Material018_0.geometry} material={materials['Material.018']} />
            <mesh geometry={nodes.Cube027_Material011_0.geometry} material={materials['Material.011']} />
          </group>
          <group position={[-257.474, 389.418, -110.137]} rotation={[-Math.PI / 2, 0, 0]} scale={[201.96, 33.29, 355.611]}>
            <mesh geometry={nodes.Cube028_Material022_0.geometry} material={materials['Material.022']} />
            <mesh geometry={nodes.Cube028_Material011_0.geometry} material={materials['Material.011']} />
          </group>
          <group position={[-263.444, 400.109, -91.876]} rotation={[-Math.PI / 2, 0, 0]} scale={[235.809, 133.15, 465.821]}>
            <mesh geometry={nodes.Cube029_Material019_0.geometry} material={materials['Material.019']} />
            <mesh geometry={nodes.Cube029_Material011_0.geometry} material={materials['Material.011']} />
          </group>
          <group position={[-262.722, 392.929, -123.384]} rotation={[-Math.PI / 2, 0, 0]} scale={[235.809, 95.763, 387.652]}>
            <mesh geometry={nodes.Cube030_Material026_0.geometry} material={materials['Material.026']} />
            <mesh geometry={nodes.Cube030_Material011_0.geometry} material={materials['Material.011']} />
          </group>
          <group position={[-255.001, 388.642, -209.273]} rotation={[-Math.PI / 2, 0, 0]} scale={[235.809, 36.293, 348.755]}>
            <mesh geometry={nodes.Cube031_Material021_0.geometry} material={materials['Material.021']} />
            <mesh geometry={nodes.Cube031_Material011_0.geometry} material={materials['Material.011']} />
          </group>
          <group position={[-263.444, 400.109, -63.851]} rotation={[-Math.PI / 2, 0, 0]} scale={[235.809, 133.15, 465.821]}>
            <mesh geometry={nodes.Cube032_Material019_0.geometry} material={materials['Material.019']} />
            <mesh geometry={nodes.Cube032_Material011_0.geometry} material={materials['Material.011']} />
          </group>
          <group position={[-263.444, 400.109, -36.583]} rotation={[-Math.PI / 2, 0, 0]} scale={[235.809, 133.15, 465.821]}>
            <mesh geometry={nodes.Cube033_Material019_0.geometry} material={materials['Material.019']} />
            <mesh geometry={nodes.Cube033_Material011_0.geometry} material={materials['Material.011']} />
          </group>
          <group position={[-263.444, 400.109, -8.558]} rotation={[-Math.PI / 2, 0, 0]} scale={[235.809, 133.15, 465.821]}>
            <mesh geometry={nodes.Cube034_Material019_0.geometry} material={materials['Material.019']} />
            <mesh geometry={nodes.Cube034_Material011_0.geometry} material={materials['Material.011']} />
          </group>
          <group position={[-266.584, 389.091, 10.802]} rotation={[-Math.PI / 2, 0, 0]} scale={[201.96, 45.561, 355.611]}>
            <mesh geometry={nodes.Cube035_Material015_0.geometry} material={materials['Material.015']} />
            <mesh geometry={nodes.Cube035_Material011_0.geometry} material={materials['Material.011']} />
          </group>
          <group position={[-266.338, 400.082, 197.884]} rotation={[-Math.PI / 2, 0, 0]} scale={[235.809, 36.582, 465.821]}>
            <mesh geometry={nodes.Cube036_Material016_0.geometry} material={materials['Material.016']} />
            <mesh geometry={nodes.Cube036_Material011_0.geometry} material={materials['Material.011']} />
          </group>
          <group position={[-265.937, 392.602, 37.063]} rotation={[-Math.PI / 2, 0, 0]} scale={[235.809, 109.916, 387.652]}>
            <mesh geometry={nodes.Cube037_Material028_0.geometry} material={materials['Material.028']} />
            <mesh geometry={nodes.Cube037_Material011_0.geometry} material={materials['Material.011']} />
          </group>
          <group position={[-265.936, 387.413, 53.267]} rotation={[-Math.PI / 2, 0, 0]} scale={[235.809, 52.512, 348.755]}>
            <mesh geometry={nodes.Cube038_Material029_0.geometry} material={materials['Material.029']} />
            <mesh geometry={nodes.Cube038_Material011_0.geometry} material={materials['Material.011']} />
          </group>
          <group position={[-265.624, 389.374, 114.244]} rotation={[-Math.PI / 2, 0, 0]} scale={[201.96, 33.29, 355.611]}>
            <mesh geometry={nodes.Cube039_Material022_0.geometry} material={materials['Material.022']} />
            <mesh geometry={nodes.Cube039_Material011_0.geometry} material={materials['Material.011']} />
          </group>
          <group position={[-268.249, 405.8, 65.709]} rotation={[-Math.PI / 2, 0, 0]} scale={[235.809, 53.872, 521.759]}>
            <mesh geometry={nodes.Cube040_Material023_0.geometry} material={materials['Material.023']} />
            <mesh geometry={nodes.Cube040_Material011_0.geometry} material={materials['Material.011']} />
          </group>
          <group position={[-266.618, 392.884, 82.729]} rotation={[-Math.PI / 2, 0, 0]} scale={[235.809, 95.763, 387.652]}>
            <mesh geometry={nodes.Cube041_Material030_0.geometry} material={materials['Material.030']} />
            <mesh geometry={nodes.Cube041_Material011_0.geometry} material={materials['Material.011']} />
          </group>
          <group position={[-264.792, 388.597, 103.203]} rotation={[-Math.PI / 2, 0, 0]} scale={[235.809, 101.201, 348.755]}>
            <mesh geometry={nodes.Cube042_Material021_0.geometry} material={materials['Material.021']} />
            <mesh geometry={nodes.Cube042_Material011_0.geometry} material={materials['Material.011']} />
          </group>
          <group position={[-268.243, 380.302, 184.818]} rotation={[-Math.PI / 2, 0, 0]} scale={[201.96, 85.355, 265.912]}>
            <mesh geometry={nodes.Cube043_Material015_0.geometry} material={materials['Material.015']} />
            <mesh geometry={nodes.Cube043_Material011_0.geometry} material={materials['Material.011']} />
          </group>
          <group position={[-266.092, 400.836, 138.743]} rotation={[-Math.PI / 2, 0, 0]} scale={[235.809, 72.878, 465.821]}>
            <mesh geometry={nodes.Cube044_Material031_0.geometry} material={materials['Material.031']} />
            <mesh geometry={nodes.Cube044_Material011_0.geometry} material={materials['Material.011']} />
          </group>
          <group position={[-267.48, 393.356, 158.096]} rotation={[-Math.PI / 2, 0, 0]} scale={[192.737, 109.916, 387.652]}>
            <mesh geometry={nodes.Cube045_Material021_0.geometry} material={materials['Material.021']} />
            <mesh geometry={nodes.Cube045_Material011_0.geometry} material={materials['Material.011']} />
          </group>
          <group position={[-268.775, 388.167, 172.477]} rotation={[-Math.PI / 2, 0, 0]} scale={[235.809, 28.855, 348.755]}>
            <mesh geometry={nodes.Cube046_Material018_0.geometry} material={materials['Material.018']} />
            <mesh geometry={nodes.Cube046_Material011_0.geometry} material={materials['Material.011']} />
          </group>
          <group position={[-262.566, 388.912, 20.944]} rotation={[-Math.PI / 2, 0, 0]} scale={[201.96, 33.29, 355.611]}>
            <mesh geometry={nodes.Cube047_Material022_0.geometry} material={materials['Material.022']} />
            <mesh geometry={nodes.Cube047_Material011_0.geometry} material={materials['Material.011']} />
          </group>
          <group position={[-265.354, 381.565, 236.079]} rotation={[-Math.PI / 2, 0, 0]} scale={[189.956, 124.899, 276.44]}>
            <mesh geometry={nodes.Cube048_Material027_0.geometry} material={materials['Material.027']} />
            <mesh geometry={nodes.Cube048_Material011_0.geometry} material={materials['Material.011']} />
          </group>
          <group position={[-264.632, 392.423, 213.096]} rotation={[-Math.PI / 2, 0, 0]} scale={[189.956, 95.763, 387.652]}>
            <mesh geometry={nodes.Cube049_Material032_0.geometry} material={materials['Material.032']} />
            <mesh geometry={nodes.Cube049_Material011_0.geometry} material={materials['Material.011']} />
          </group>
          <group position={[-269.214, 389.352, 126.097]} rotation={[-Math.PI / 2, 0, 0]} scale={[235.809, 36.293, 348.755]}>
            <mesh geometry={nodes.Cube050_Material022_0.geometry} material={materials['Material.022']} />
            <mesh geometry={nodes.Cube050_Material011_0.geometry} material={materials['Material.011']} />
          </group>
          <group position={[-265.354, 381.565, 261.993]} rotation={[-Math.PI / 2, 0, 0]} scale={[189.956, 124.899, 276.44]}>
            <mesh geometry={nodes.Cube051_Material019_0.geometry} material={materials['Material.019']} />
            <mesh geometry={nodes.Cube051_Material011_0.geometry} material={materials['Material.011']} />
          </group>
          <group position={[-265.354, 381.565, 287.994]} rotation={[-Math.PI / 2, 0, 0]} scale={[189.956, 124.899, 276.44]}>
            <mesh geometry={nodes.Cube052_Material019_0.geometry} material={materials['Material.019']} />
            <mesh geometry={nodes.Cube052_Material011_0.geometry} material={materials['Material.011']} />
          </group>
          <group position={[-265.354, 381.565, 314.331]} rotation={[-Math.PI / 2, 0, 0]} scale={[189.956, 124.899, 276.44]}>
            <mesh geometry={nodes.Cube053_Material019_0.geometry} material={materials['Material.019']} />
            <mesh geometry={nodes.Cube053_Material011_0.geometry} material={materials['Material.011']} />
          </group>
          <mesh geometry={nodes.Cube012_Mustard_0.geometry} material={materials.Mustard} position={[-57.74, 14.561, -160.006]} rotation={[-Math.PI / 2, 0, 0]} scale={[139.726, 126.11, 1.101]} />
          <mesh geometry={nodes.Cube_Couch_0.geometry} material={materials.Couch} position={[190.654, 74.856, -73.185]} rotation={[-Math.PI / 2, 0, 0]} scale={[59.881, 82.561, 16.086]} />
          <mesh geometry={nodes.Cube005_Couch_0.geometry} material={materials.Couch} position={[191.223, 75.115, -239.699]} rotation={[-Math.PI / 2, 0, 0]} scale={[59.881, 82.561, 16.086]} />
          <mesh geometry={nodes.Couch_Couch_0.geometry} material={materials.Couch} position={[233.344, 39.784, -175.053]} rotation={[-Math.PI / 2, 0, 0]} scale={[59.624, 189.181, 35.236]} />
          <mesh geometry={nodes.Cube006_Mustard_0.geometry} material={materials.Mustard} position={[216.217, 131.243, -281.4]} rotation={[-1.02, -0.553, 0.161]} scale={[34.815, 39.25, 9.353]} />
          <mesh geometry={nodes.Cube010_Desk_0.geometry} material={materials.Desk} position={[-271.99, 349.402, -16.736]} rotation={[-Math.PI / 2, 0, 0]} scale={[26.437, 350.581, 3.487]} />
          <mesh geometry={nodes.Cube011_Desk_0.geometry} material={materials.Desk} position={[-271.99, 231.7, -16.736]} rotation={[-Math.PI / 2, 0, 0]} scale={[26.437, 350.581, 3.487]} />
          <mesh geometry={nodes.Cube007_Desk_0.geometry} material={materials.Desk} position={[-260.643, 132.049, -179.488]} rotation={[-Math.PI / 2, 0, 0]} scale={[36.62, 107.113, 25.38]} />
          <mesh geometry={nodes.Cube008_Desk_0.geometry} material={materials.Desk} position={[-225.799, 131.79, -127.795]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={[17.21, 48.141, 3.025]} />
          <mesh geometry={nodes.Cube009_Desk_0.geometry} material={materials.Desk} position={[-225.799, 131.79, -128.402]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={[17.21, 48.141, 3.025]} />
          <mesh geometry={nodes.Seat_Seat_0.geometry} material={materials.Seat} position={[-94.041, 84.337, 145.799]} rotation={[-Math.PI / 2, 0, 0.842]} scale={[40.81, 35.482, 3.213]} />
          <mesh geometry={nodes.Legs_PC001_0.geometry} material={materials['PC.001']} position={[-153.836, 63.248, 211.152]} rotation={[-Math.PI / 2, 0, 0.842]} scale={[145.355, 85.005, 30.871]} />
          <mesh geometry={nodes.Cube013_PC_0.geometry} material={materials.material} position={[-245.803, 169.737, -106.477]} rotation={[-Math.PI / 2, 0, 0.396]} scale={[5.063, 19.216, 12.37]} />
          <mesh geometry={nodes.Icosphere_Floor_0.geometry} material={materials.Floor} position={[-266.713, 248.896, 23.089]} rotation={[-2.134, 0, 0]} scale={[139.586, 163.984, 163.984]} />
          <mesh geometry={nodes.Icosphere001_Floor_0.geometry} material={materials.Floor} position={[-258.685, 248.706, 55.884]} rotation={[-Math.PI / 2, 1.406, 0]} scale={[141.613, 138.461, 140.296]} />
          <mesh geometry={nodes.Cube014_Floor_0.geometry} material={materials.Floor} position={[-266.678, 247.757, 86.405]} rotation={[-Math.PI / 2, 0, 0]} scale={[119.635, 126.964, 125.306]} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/video-models/comp-room.glb')
